# Generated by Django 3.1.2 on 2022-04-07 13:47

from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DingAppTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('corp_id', models.CharField(db_index=True, default='', max_length=100, verbose_name='企业corpId')),
                ('app_name', models.CharField(default='', max_length=100, unique=True, verbose_name='钉钉应用名称')),
                ('agent_id', models.IntegerField(default=0, unique=True, verbose_name='应用 appId')),
                ('app_key', models.CharField(default='', max_length=200, verbose_name='应用 appKey')),
                ('app_secret', models.CharField(default='', max_length=500, verbose_name='应用 appSecret')),
                ('app_token', models.CharField(db_index=True, default='', max_length=500, verbose_name='外部调用的唯一Token')),
                ('expire_time', models.BigIntegerField(default=0, verbose_name='Token过期时间')),
                ('env', models.SmallIntegerField(choices=[(0, '测试环境'), (1, '生产环境')], default=0, verbose_name='Token所属环境')),
            ],
            options={
                'db_table': 'circle_ding_app_token',
            },
        ),
        migrations.CreateModel(
            name='DingMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('msg_title', models.CharField(blank=True, default='', max_length=500, verbose_name='消息标题')),
                ('msg_media', models.CharField(blank=True, default='', max_length=500, verbose_name='消息图片')),
                ('msg_type', models.SmallIntegerField(blank=True, choices=[(1, 'text'), (2, 'image'), (3, 'voice'), (4, 'file'), (5, 'link'), (6, 'oa'), (7, 'markdown'), (8, 'action_card')], default=0, verbose_name='消息类型')),
                ('msg_type_cn', models.CharField(blank=True, default='', max_length=20, verbose_name='消息类型')),
                ('msg_text', models.CharField(blank=True, default='', max_length=1000, verbose_name='消息文本')),
                ('msg_url', models.CharField(blank=True, default='', max_length=500, verbose_name='消息链接')),
                ('msg_pc_url', models.CharField(blank=True, default='', max_length=500, verbose_name='PC消息链接')),
                ('source', models.SmallIntegerField(blank=True, choices=[(1, '星喜积分'), (2, '问卷投票'), (3, '星圈话题')], default=0, verbose_name='推送来源')),
                ('source_cn', models.CharField(blank=True, default='', max_length=200, verbose_name='推送来源')),
                ('ihcm_survey_id', models.IntegerField(blank=True, default=0, verbose_name='Odoo问卷投票id')),
                ('app', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ding_talk.dingapptokenmodel', verbose_name='微应用id')),
            ],
            options={
                'db_table': 'circle_ding_message_info',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DingMsgPushLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sender', models.CharField(blank=True, default='sys', max_length=100, verbose_name='推送人(默认系统)')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='推送时间')),
                ('receiver_mobile', models.TextField(blank=True, default='', max_length=20, verbose_name='接收人手机号')),
                ('receiver_job_code', models.TextField(blank=True, default='', max_length=100, verbose_name='接收人钉钉jobCode')),
                ('receive_time', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='接收时间')),
                ('is_read', models.BooleanField(blank=True, default=False, verbose_name='接收人是否已读')),
                ('read_time', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='接收人已读时间')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='推送是否成功')),
                ('traceback', models.CharField(blank=True, default='', max_length=2000, verbose_name='推送异常')),
                ('task_id', models.BigIntegerField(blank=True, db_index=True, default=0, verbose_name='钉钉创建的异步发送任务ID')),
                ('request_id', models.CharField(blank=True, default='', max_length=100, verbose_name='钉钉推送的请求ID')),
                ('msg_uid', models.BigIntegerField(blank=True, default=0, unique=True, verbose_name='消息唯一id')),
                ('is_recall', models.BooleanField(blank=True, default=False, verbose_name='消息是否撤回')),
                ('recall_time', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='撤回时间')),
                ('is_test', models.BooleanField(blank=True, default=False, verbose_name='是否测试消息')),
                ('is_done', models.BooleanField(blank=True, default=False, verbose_name='是否完成(问卷投票等)')),
                ('ding_msg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ding_talk.dingmessagemodel', verbose_name='钉钉消息')),
            ],
            options={
                'db_table': 'circle_ding_msg_push_log',
                'ordering': ['-id'],
            },
        ),
    ]
