# Generated by Django 3.1.2 on 2022-04-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingmsgpushlogmodel',
            name='ding_msg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ding_msg', to='ding_talk.dingmessagemodel', verbose_name='钉钉消息'),
        ),
    ]
