# Generated by Django 3.1.2 on 2022-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0002_auto_20220408_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingmsgpushlogmodel',
            name='msg_uid',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='消息唯一id'),
        ),
        migrations.AlterField(
            model_name='dingmsgpushlogmodel',
            name='receiver_job_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='接收人钉钉jobCode'),
        ),
        migrations.AlterField(
            model_name='dingmsgpushlogmodel',
            name='receiver_mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='接收人手机号'),
        ),
        migrations.AlterField(
            model_name='dingmsgpushlogmodel',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='钉钉创建的异步发送任务ID'),
        ),
    ]
