# Generated by Django 3.1.2 on 2022-06-18 17:35

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base
import fosun_circle.libs.path_builder


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0004_auto_20220412_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingAppMediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('media_type', models.SmallIntegerField(blank=True, choices=[(1, 'image'), (2, 'file'), (3, 'image')], default=1, verbose_name='媒体类型')),
                ('media_title', models.CharField(blank=True, default='', max_length=500, verbose_name='媒体名称')),
                ('media_id', models.CharField(blank=True, default='', max_length=100, verbose_name='媒体id')),
                ('media', models.FileField(blank=True, max_length=500, storage=django.core.files.storage.FileSystemStorage(), upload_to=fosun_circle.libs.path_builder.PathBuilder('media'), verbose_name='媒体链接')),
                ('key', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='上传文件key')),
                ('media_url', models.URLField(blank=True, default='', max_length=500, verbose_name='媒体文件URL')),
                ('file_size', models.IntegerField(blank=True, default=0, verbose_name='文件大小')),
                ('check_sum', models.CharField(blank=True, default='', max_length=64, verbose_name='源文件md5')),
                ('src_filename', models.CharField(blank=True, default='', max_length=200, verbose_name='源文件名称')),
                ('post_filename', models.CharField(blank=True, default='', max_length=200, verbose_name='处理后的文件名称')),
                ('is_share', models.BooleanField(blank=True, default=False, verbose_name='是否共享')),
                ('access_token', models.CharField(blank=True, default='', max_length=100, verbose_name='token秘钥(如果不共享)')),
                ('app', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ding_talk.dingapptokenmodel', verbose_name='微应用id')),
            ],
            options={
                'db_table': 'circle_ding_app_media',
                'ordering': ['-create_time'],
            },
        ),
    ]
