# Generated by Django 3.1.2 on 2022-06-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0007_auto_20220618_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingappmediamodel',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ding_talk.dingapptokenmodel', verbose_name='微应用id'),
        ),
    ]
