# Generated by Django 3.1.2 on 2022-06-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0009_auto_20220618_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingappmediamodel',
            name='is_success',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否成功'),
        ),
        migrations.AlterField(
            model_name='dingappmediamodel',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='ding_talk.dingapptokenmodel', verbose_name='微应用id'),
        ),
    ]
