# Generated by Django 3.1.14 on 2023-02-02 14:48

from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0012_auto_20221117_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingMsgRecallLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='撤回消息的任务ID')),
                ('recall_time', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='撤回时间')),
                ('recall_cnt', models.IntegerField(blank=True, default=0, verbose_name='撤回消息数量')),
                ('app', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ding_talk.dingapptokenmodel', verbose_name='微应用id')),
                ('ding_msg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ding_talk.dingmessagemodel', verbose_name='钉钉消息')),
            ],
            options={
                'db_table': 'circle_ding_msg_recall_log',
                'ordering': ['-id'],
            },
        ),
    ]
