# Generated by Django 3.1.14 on 2023-02-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0013_dingmsgrecalllogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingmsgrecalllogmodel',
            name='recall_ret',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='撤回消息的结果'),
        ),
    ]
