# Generated by Django 3.1.14 on 2023-02-09 12:19

from django.db import migrations, models
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0014_dingmsgrecalllogmodel_recall_ret'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingPeriodicTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('beat_cron_id', models.IntegerField(blank=True, default=0, verbose_name='定时任务id')),
                ('beat_periodic_task_id', models.IntegerField(blank=True, default=0, verbose_name='定时任务')),
                ('cron_expr', models.CharField(blank=True, default='', max_length=100, verbose_name='定时表达式')),
                ('message_ids', models.TextField(blank=True, default='', verbose_name='钉钉消息id')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='定时任务说明')),
            ],
            options={
                'db_table': 'circle_ding_periodic_task',
                'ordering': ['-id'],
            },
        ),
    ]
