# Generated by Django 3.1.14 on 2023-02-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0015_dingperiodictaskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dingperiodictaskmodel',
            name='message_ids',
        ),
        migrations.AddField(
            model_name='dingperiodictaskmodel',
            name='cron_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='定时任务名称'),
        ),
        migrations.AlterField(
            model_name='dingperiodictaskmodel',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='任务说明'),
        ),
    ]
