# Generated by Django 3.1.14 on 2023-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0016_auto_20230212_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingmsgrecalllogmodel',
            name='msg_uid',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='撤回消息UID'),
        ),
    ]
