# Generated by Django 3.1.14 on 2023-02-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0017_dingmsgrecalllogmodel_msg_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingmsgrecalllogmodel',
            name='is_recall_ok',
            field=models.BooleanField(blank=True, default=False, verbose_name='状态'),
        ),
    ]
