# Generated by Django 3.1.14 on 2023-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0018_dingmsgrecalllogmodel_is_recall_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingperiodictaskmodel',
            name='max_run_times',
            field=models.IntegerField(blank=True, default=0, verbose_name='定时任务最大执行次数'),
        ),
    ]
