# Generated by Django 3.1.14 on 2023-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0019_dingperiodictaskmodel_max_run_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingperiodictaskmodel',
            name='deadline_run_time',
            field=models.DateTimeField(blank=True, help_text='截止执行时间', null=True, verbose_name='截止执行时间'),
        ),
    ]
