# Generated by Django 3.1.14 on 2023-03-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0020_dingperiodictaskmodel_deadline_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingperiodictaskmodel',
            name='message_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='推送消息话题ID'),
        ),
        migrations.AddField(
            model_name='dingperiodictaskmodel',
            name='push_range',
            field=models.CharField(blank=True, default='{}', max_length=5000, verbose_name='话题推送范围(JSON格式)'),
        ),
    ]
