# Generated by Django 3.1.14 on 2023-04-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0021_auto_20230303_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dingapptokenmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='dingmessagemodel',
            name='source',
            field=models.SmallIntegerField(blank=True, choices=[(1, '星喜积分'), (2, '问卷投票'), (3, '星圈话题'), (4, '节日关怀')], default=0, verbose_name='推送来源'),
        ),
    ]
