# Generated by Django 3.1.14 on 2023-04-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0022_auto_20230410_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dingmsgpushlogmodel',
            name='ding_msg',
        ),
        migrations.AddField(
            model_name='dingmsgpushlogmodel',
            name='ding_msg_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='钉钉消息'),
        ),
    ]
