# Generated by Django 3.1.14 on 2023-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0023_auto_20230414_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dingmsgrecalllogmodel',
            name='app',
        ),
        migrations.RemoveField(
            model_name='dingmsgrecalllogmodel',
            name='ding_msg',
        ),
        migrations.AddField(
            model_name='dingmsgrecalllogmodel',
            name='app_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='微应用id'),
        ),
        migrations.AddField(
            model_name='dingmsgrecalllogmodel',
            name='ding_msg_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='钉钉消息id'),
        ),
        migrations.AlterField(
            model_name='dingmsgpushlogmodel',
            name='ding_msg_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='钉钉消息ID'),
        ),
    ]
