# Generated by Django 3.1.14 on 2023-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0024_auto_20230415_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingmessagemodel',
            name='source',
            field=models.SmallIntegerField(blank=True, choices=[(1, '星喜积分'), (2, '问卷投票'), (3, '星圈话题'), (4, '节日关怀'), (5, '星喜甄选')], default=0, verbose_name='推送来源'),
        ),
    ]
