# Generated by Django 3.1.14 on 2023-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ding_talk', '0027_auto_20231130_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingmsgpushlogmodel',
            name='max_times',
            field=models.IntegerField(blank=True, default=1, verbose_name='消息是失败最大补偿推送次数'),
        ),
    ]
