# Generated by Django 3.1.14 on 2023-06-05 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('published_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='发布时间')),
                ('save_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='暂存时间')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('img_url', models.CharField(blank=True, default='', max_length=500, verbose_name='图片')),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, '草稿'), (1, '暂存'), (2, '发布'), (3, '进行中'), (4, '关闭')], default=0, verbose_name='状态')),
                ('source', models.CharField(blank=True, choices=[('my', '自建问卷'), ('ihcm', 'Odoo问卷')], default='my', max_length=10, verbose_name='来源')),
                ('is_anonymous', models.BooleanField(blank=True, default=False, verbose_name='是否匿名')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '问卷表',
                'verbose_name_plural': '问卷表',
                'db_table': 'circle_survey_questionnaire',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SelectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, '单选题'), (2, '多选题(图片)'), (3, '单项文本'), (4, '多项文本'), (5, '打分题')], default=0, verbose_name='题型')),
                ('widget', models.CharField(blank=True, default='', max_length=200, verbose_name='题型组件')),
                ('desc', models.CharField(blank=True, default='', max_length=200, verbose_name='题型描述')),
            ],
            options={
                'verbose_name': '题目类型表',
                'verbose_name_plural': '题目类型表',
                'db_table': 'circle_survey_selection',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, '草稿'), (1, '暂存'), (2, '提交')], default=0, verbose_name='提交状态')),
                ('submit_time', models.DateTimeField(blank=True, default=True, null=True, verbose_name='问卷提交时间')),
                ('questionnaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairemodel', verbose_name='问卷id')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='问卷提交者')),
            ],
            options={
                'verbose_name': '问卷用户提交表',
                'verbose_name_plural': '问卷用户提交表',
                'db_table': 'circle_survey_submission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='题目标题')),
                ('desc', models.CharField(blank=True, default='', max_length=200, verbose_name='题目说明')),
                ('img_url', models.CharField(blank=True, default='', max_length=500, verbose_name='题目图片补充')),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='题目顺序')),
                ('rows', models.SmallIntegerField(blank=True, default=0, verbose_name='行数')),
                ('is_required', models.BooleanField(blank=True, default=True, verbose_name='是否必填')),
                ('questionnaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairemodel', verbose_name='问卷id')),
                ('topic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.selectionmodel', verbose_name='题目类型id')),
            ],
            options={
                'verbose_name': '问题表',
                'verbose_name_plural': '问题表',
                'db_table': 'circle_survey_question',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OptionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='选项名')),
                ('order', models.SmallIntegerField(blank=True, default=0, verbose_name='选项顺序')),
                ('min_value', models.CharField(blank=True, default='', max_length=100, verbose_name='最小值(打分题)')),
                ('max_value', models.CharField(blank=True, default='', max_length=100, verbose_name='最大值(打分题)')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionmodel', verbose_name='关联题目id')),
            ],
            options={
                'verbose_name': '问卷中问题选项表',
                'verbose_name_plural': '问卷中问题选项表',
                'db_table': 'circle_survey_options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('answer', models.CharField(blank=True, default='', max_length=500, verbose_name='问题答案')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionmodel', verbose_name='问题id')),
                ('questionnaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairemodel', verbose_name='问卷id')),
                ('submission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.submissionmodel', verbose_name='提交id')),
            ],
            options={
                'verbose_name': '问卷用户提交表',
                'verbose_name_plural': '问卷用户提交表',
                'db_table': 'circle_survey_answer',
                'ordering': ['id'],
            },
        ),
    ]
