# Generated by Django 3.1.14 on 2023-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', '草稿'), ('open', '进行中'), ('close', '关闭')], default=0, max_length=10, verbose_name='状态'),
        ),
    ]
