# Generated by Django 3.1.14 on 2023-06-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20230606_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairemodel',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='说明'),
        ),
    ]
