# Generated by Django 3.1.14 on 2023-05-22 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='抽奖活动名称')),
                ('participant_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='参与抽奖人数')),
                ('awarded_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='已中奖人数')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, null=True, verbose_name='已确认抽奖')),
                ('is_pushed', models.BooleanField(blank=True, default=False, null=True, verbose_name='中奖消息已推送')),
                ('state', models.CharField(blank=True, choices=[('SET_CONDITION', '设置参与条件'), ('CONFIRM_PARTICIPANT', '确认参与人员名单'), ('SET_AWARD', '设置奖品'), ('LOTTERY', '抽奖'), ('PUSH_MESSAGE', '推送中奖消息')], default='SET_CONDITION', max_length=50, null=True, verbose_name='抽奖节点状态')),
                ('participant_mode', models.CharField(blank=True, choices=[('circle', '星圈话题参与'), ('excel', 'Excel导入')], default='circle', max_length=20, null=True, verbose_name='参与模式')),
                ('circle_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='话题id')),
                ('is_posted', models.BooleanField(blank=True, default=False, null=True, verbose_name='已发帖')),
                ('is_commented', models.BooleanField(blank=True, default=False, null=True, verbose_name='已评论')),
                ('is_liked', models.BooleanField(blank=True, default=False, null=True, verbose_name='已点赞')),
                ('deadline', models.DateTimeField(blank=True, default=None, null=True, verbose_name='截止时间')),
            ],
            options={
                'db_table': 'circle_lottery_activity',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AwardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='奖品名称')),
                ('desc', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='奖品描述')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('img_url', models.URLField(blank=True, default='', max_length=500, null=True, verbose_name='奖品链接')),
                ('award_type', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='奖品类型')),
                ('activity_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lottery.activitymodel')),
            ],
            options={
                'db_table': 'circle_lottery_award',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Mobile')),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Username')),
                ('is_awarded', models.BooleanField(blank=True, default=False, null=True, verbose_name='已获奖')),
                ('is_pushed', models.BooleanField(blank=True, default=False, null=True, verbose_name='中奖消息已推送')),
                ('is_recall', models.BooleanField(blank=True, default=False, null=True, verbose_name='中奖消息已撤回')),
                ('activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lottery_participants', to='lottery.activitymodel')),
                ('award', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lottery_winners', to='lottery.awardmodel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_lottery_participant',
                'ordering': ['-id'],
            },
        ),
    ]
