# Generated by Django 3.1.14 on 2023-05-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardmodel',
            old_name='count',
            new_name='num',
        ),
    ]
