# Generated by Django 3.1.14 on 2023-05-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20230523_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymodel',
            name='participant_mode',
            field=models.CharField(blank=True, choices=[('CIRCLE', '星圈话题参与'), ('EXCEL', 'Excel导入')], default='circle', max_length=20, null=True, verbose_name='参与模式'),
        ),
    ]
