# Generated by Django 3.1.14 on 2023-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_auto_20230523_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymodel',
            name='circle_id',
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='tag_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='话题标签'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='participant_mode',
            field=models.CharField(blank=True, choices=[('CIRCLE', '星圈话题参与'), ('EXCEL', 'Excel导入')], default='CIRCLE', max_length=20, null=True, verbose_name='参与模式'),
        ),
    ]
