# Generated by Django 3.1.14 on 2023-05-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20230523_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardmodel',
            old_name='activity_id',
            new_name='activity',
        ),
    ]
