# Generated by Django 3.1.14 on 2023-04-13 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Menu Name')),
                ('icon', models.CharField(blank=True, default='', max_length=200, verbose_name='Menu Icon')),
                ('app', models.CharField(blank=True, default='', max_length=200, verbose_name='Menu Belong to App')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='Menu Url')),
                ('component_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Vue Component Name')),
                ('parent_id', models.IntegerField(blank=True, default=1, verbose_name='Parent Menu ID')),
                ('level', models.SmallIntegerField(blank=True, choices=[(1, '一级菜单'), (2, '二级菜单')], default=1, verbose_name='Menu Level')),
            ],
            options={
                'db_table': 'circle_permission_menu',
            },
        ),
        migrations.CreateModel(
            name='MenuOwnerPermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permissions.menumodel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_permission_menu_owner',
            },
        ),
        migrations.AddField(
            model_name='menumodel',
            name='permissions',
            field=models.ManyToManyField(through='permissions.MenuOwnerPermissionModel', to=settings.AUTH_USER_MODEL, verbose_name='Owner Permission'),
        ),
    ]
