# Generated by Django 3.1.14 on 2023-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_remove_menumodel_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='order',
            field=models.IntegerField(blank=True, default=1, verbose_name='Menu Order'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='Parent Menu ID'),
        ),
    ]
