# Generated by Django 3.1.14 on 2023-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20230413_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumodel',
            old_name='order',
            new_name='menu_order',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='submenu_order',
            field=models.IntegerField(blank=True, default=1, verbose_name='Submenu Order'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(1, '一级菜单'), (2, '二级菜单'), (3, '三级菜单')], default=1, verbose_name='Menu Level'),
        ),
    ]
