# Generated by Django 3.1.14 on 2023-04-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20230413_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='submenu_order',
        ),
    ]
