# Generated by Django 3.1.14 on 2023-05-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20230526_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupmodel',
            table='circle_permission_group',
        ),
    ]
