# Generated by Django 3.1.14 on 2023-05-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_auto_20230526_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuOwnerPermissionModel',
        ),
    ]
