# Generated by Django 3.1.14 on 2023-08-11 13:23

from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0010_delete_menuownerpermissionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInvokerClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Invoker Client')),
                ('client_id', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Invoker Client ID')),
                ('salt', models.CharField(blank=True, default=None, max_length=16, verbose_name='Token Salt')),
                ('app_key', models.CharField(blank=True, default='', max_length=100, verbose_name='AppKey')),
                ('app_secret', models.CharField(blank=True, default='', max_length=200, verbose_name='AppSecret')),
                ('access_token', models.CharField(blank=True, default='', max_length=500, verbose_name='Token')),
                ('expire_at', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='Expiration')),
                ('remark', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Token')),
            ],
            options={
                'db_table': 'circle_permission_api_invoker_client',
            },
        ),
        migrations.CreateModel(
            name='ApiProviderUriModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('url', models.CharField(blank=True, default='', max_length=200, verbose_name='Invoker URL')),
                ('invoker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permissions.apiinvokerclientmodel')),
            ],
            options={
                'db_table': 'circle_permission_api_invoker_url',
            },
        ),
    ]
