# Generated by Django 3.1.14 on 2023-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0011_apiinvokerclientmodel_apiproviderurimodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiProviderUriModel',
            new_name='ApiInvokerUriModel',
        ),
        migrations.AlterField(
            model_name='apiinvokerclientmodel',
            name='app_key',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='AppKey'),
        ),
        migrations.AlterField(
            model_name='apiinvokerclientmodel',
            name='client_id',
            field=models.CharField(blank=True, max_length=8, verbose_name='Invoker Client ID'),
        ),
    ]
