# Generated by Django 3.1.14 on 2023-08-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0012_auto_20230814_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinvokerurimodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Invoker Name'),
        ),
    ]
