# Generated by Django 3.1.14 on 2023-08-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0013_apiinvokerurimodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiinvokerurimodel',
            options={'ordering': ['-id']},
        ),
    ]
