# Generated by Django 3.1.14 on 2023-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0014_auto_20230817_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodel',
            options={'ordering': ('parent_id', 'level', 'menu_order')},
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Desc'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Group Name'),
        ),
    ]
