# Generated by Django 3.1.14 on 2023-10-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0015_auto_20231031_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmodel',
            options={'ordering': ('id',)},
        ),
    ]
