# Generated by Django 3.1.14 on 2023-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0016_auto_20231031_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(0, '根'), (1, '一级菜单'), (2, '二级菜单'), (3, '三级菜单')], default=1, verbose_name='Menu Level'),
        ),
    ]
