HOME_BACKGROUND_URL = "http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1"
REQUEST_PARAMS_NEGOTIATOR_CAMEL = "PARAMS_NEGOTIATOR_CAMEL"
RESPONSE_CONTENT_NEGOTIATOR_CAMEL = "CONTENT_NEGOTIATOR_CAMEL"

