# Generated by Django 3.1.14 on 2022-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleactionlogmodel',
            name='circle_id',
            field=models.IntegerField(default=None, null=True, verbose_name='帖子id'),
        ),
        migrations.AlterField(
            model_name='circleactionlogmodel',
            name='comment_id',
            field=models.IntegerField(default=None, null=True, verbose_name='评论id'),
        ),
    ]
