# Generated by Django 3.1.14 on 2022-10-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20221010_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleactionlogmodel',
            name='operator_mobile',
            field=models.CharField(default='', max_length=20, verbose_name='操作者手机号'),
        ),
    ]
