# Generated by Django 3.1.14 on 2022-10-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_circleactionlogmodel_operator_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleactionlogmodel',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='帖子是否匿名'),
        ),
    ]
