# Generated by Django 3.1.14 on 2022-11-03 15:45

from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0004_circleactionlogmodel_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleMessageBodyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='标题')),
                ('media_id', models.CharField(blank=True, default='', max_length=500, verbose_name='媒体')),
                ('msg_type', models.SmallIntegerField(blank=True, choices=[('text', '文本消息'), ('image', '图片消息'), ('voice', '语音消息'), ('file', '文件消息'), ('link', '链接消息'), ('oa', 'OA 消息'), ('markdown', 'markdown 消息'), ('action_card', 'action_card 消息'), ('action_card', 'action_card 消息'), ('action_card', 'action_card 消息')], default=0, verbose_name='消息类型')),
                ('msg_type_cn', models.CharField(blank=True, default='', max_length=20, verbose_name='消息类型CN')),
                ('text', models.CharField(blank=True, default='', max_length=1000, verbose_name='内容')),
                ('app_url', models.CharField(blank=True, default='', max_length=500, verbose_name='app链接')),
                ('pc_url', models.CharField(blank=True, default='', max_length=500, verbose_name='pc链接')),
                ('action_type', models.SmallIntegerField(choices=[(1, '帖子评论'), (2, '帖子点赞'), (3, '评论点赞'), (4, '帖子审核'), (5, '人事专区评论回复提醒')], default=0, unique=True, verbose_name='操作类型')),
            ],
            options={
                'db_table': 'circle_message_info',
            },
        ),
        migrations.AddField(
            model_name='circleactionlogmodel',
            name='url_params',
            field=models.CharField(default='', max_length=500, verbose_name='跳转链接参数JSON'),
        ),
        migrations.AlterField(
            model_name='circleactionlogmodel',
            name='action_type',
            field=models.SmallIntegerField(choices=[(1, '帖子评论'), (2, '帖子点赞'), (3, '评论点赞'), (4, '帖子审核'), (5, '人事专区评论回复提醒')], default=0, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='circleactionlogmodel',
            name='mobile',
            field=models.CharField(default='', max_length=20, verbose_name='消息接收者手机号(帖子、评论)'),
        ),
        migrations.AddField(
            model_name='circleactionlogmodel',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='circle.circlemessagebodymodel', verbose_name='应用消息'),
        ),
    ]
