# Generated by Django 3.1.14 on 2022-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_auto_20221103_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlemessagebodymodel',
            name='msg_type_cn',
        ),
        migrations.AlterField(
            model_name='circlemessagebodymodel',
            name='msg_type',
            field=models.CharField(blank=True, choices=[('text', '文本消息'), ('image', '图片消息'), ('voice', '语音消息'), ('file', '文件消息'), ('link', '链接消息'), ('oa', 'OA 消息'), ('markdown', 'markdown 消息'), ('action_card', 'action_card 消息'), ('action_card', 'action_card 消息'), ('action_card', 'action_card 消息')], default=0, max_length=100, verbose_name='消息类型'),
        ),
    ]
