# Generated by Django 3.1.14 on 2022-11-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0008_auto_20221104_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleactionlogmodel',
            name='push_strategy',
            field=models.SmallIntegerField(choices=[(1, '立即推送'), (2, '早上九点推送')], default=0, verbose_name='推送策略'),
        ),
    ]
