# Generated by Django 3.1.14 on 2022-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0010_auto_20221226_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleannualpersonalsummarymodel',
            name='first_circle_text',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='第一个实名帖子内容'),
        ),
    ]
