# Generated by Django 3.1.14 on 2023-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0013_auto_20230302_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleannualpersonalsummarymodel',
            name='only_visitor',
            field=models.BooleanField(default=False, null=True, verbose_name='仅访问'),
        ),
    ]
