# Generated by Django 3.1.14 on 2023-04-13 15:58

from django.db import migrations, models
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliStaticUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Name')),
                ('url', models.CharField(blank=True, default='', max_length=1000, verbose_name='URL')),
                ('key', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='key')),
                ('file_size', models.IntegerField(blank=True, default=0, verbose_name='Size')),
                ('check_sum', models.CharField(blank=True, default='', max_length=64, verbose_name='MD5')),
                ('is_share', models.BooleanField(blank=True, default=False, verbose_name='Is Public')),
                ('is_success', models.BooleanField(blank=True, default=True, verbose_name='Is Success')),
                ('access_token', models.CharField(blank=True, default='', max_length=100, verbose_name='Access Token')),
            ],
            options={
                'db_table': 'circle_aliyun_static_upload',
                'ordering': ['-create_time'],
            },
        ),
    ]
