# Generated by Django 3.1.14 on 2023-11-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alistaticuploadmodel',
            options={'ordering': ['-id']},
        ),
    ]
