# Generated by Django 3.1.2 on 2020-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleusersmodel',
            name='phone_number',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='手机号码'),
        ),
    ]
