# Generated by Django 3.1.2 on 2020-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201124_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleresourcepermissionmodel',
            name='variable_name',
            field=models.CharField(default='', max_length=100, verbose_name='字段标识'),
        ),
        migrations.AddField(
            model_name='circleusersresourcepermissionmodel',
            name='is_include',
            field=models.BooleanField(default=True, verbose_name='是否包含resource_id的资源'),
        ),
    ]
