# Generated by Django 3.1.2 on 2020-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201126_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circleresourcepermissionmodel',
            name='variable_name',
        ),
        migrations.AddField(
            model_name='circleresourcepermissionmodel',
            name='component',
            field=models.CharField(default='', max_length=100, verbose_name='所属组件'),
        ),
        migrations.AddField(
            model_name='circleresourcepermissionmodel',
            name='module_name',
            field=models.CharField(default='', max_length=100, verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='circleresourcepermissionmodel',
            name='perm_type',
            field=models.SmallIntegerField(choices=[(0, '所属Tab资源范围(首页、发现、开炼、我的 等)'), (1, '所属模块资源范围(动态： 列表、详情......)'), (2, '所属模块权限范围(动态： 创建、评论、点赞....)')], default=0, verbose_name='类型'),
        ),
    ]
