# Generated by Django 3.1.2 on 2020-11-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201127_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circleresourcepermissionmodel',
            name='parent_id',
        ),
    ]
