# Generated by Django 3.1.2 on 2020-11-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_circleresourcepermissionmodel_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleresourcepermissionmodel',
            name='param_name',
            field=models.CharField(default='', max_length=100, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='circleresourcepermissionmodel',
            name='perm_type',
            field=models.SmallIntegerField(choices=[(0, 'TabBar 资源(首页、发现、开炼、我的 等)'), (1, '模块资源(日历、动态、吐槽......)'), (2, 'TabBar 拥有的模块资源(首页: 日历、动态、吐槽...)'), (3, '模块拥有的资源范围(动态： 列表、详情......)'), (4, '模块拥有的权限范围(动态： 创建、评论、点赞....)')], default=0, verbose_name='类型'),
        ),
    ]
