# Generated by Django 3.1.2 on 2021-11-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210323_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circleusersmodel',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
