# Generated by Django 3.1.2 on 2022-02-24 08:51

from django.db import migrations, models
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211105_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbsUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phoneNumber', models.CharField(default='', max_length=20, verbose_name='手机号码')),
                ('countryCode', models.CharField(default='+86', max_length=10, verbose_name='国别')),
                ('email', models.EmailField(default='example@126.com', max_length=500, verbose_name='邮箱')),
                ('avatar', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('isJob', models.BooleanField(default=True, verbose_name='在职状态')),
                ('company', models.CharField(default='', max_length=200, verbose_name='公司名')),
                ('departmentCh', models.CharField(default='', max_length=100, verbose_name='中文部门')),
                ('departmentEn', models.CharField(default='', max_length=100, verbose_name='英文部门')),
                ('positionCh', models.CharField(blank=True, max_length=200, null=True, verbose_name='中文职位')),
                ('positionEn', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文文职位')),
                ('replyCount', models.IntegerField(default=0, verbose_name='回帖数量')),
                ('signName', models.CharField(max_length=255, null=True, verbose_name='个性签名')),
                ('nickName', models.CharField(default='', max_length=12, verbose_name='昵称')),
                ('source', models.CharField(default='SYS', max_length=12, verbose_name='用户来源')),
                ('isForbidden', models.BooleanField(default=False, verbose_name='禁止发表言论')),
                ('isAgree', models.BooleanField(default=False, verbose_name='同意用户公告')),
                ('fullname', models.CharField(default='', max_length=100, verbose_name='全名')),
                ('newCircleCount', models.IntegerField(default=0, verbose_name='新增星圈信息')),
                ('newTaleCount', models.IntegerField(default=0, verbose_name='新增召集令信息')),
                ('userType', models.SmallIntegerField(default=0, verbose_name='用户类型')),
                ('isAllowAddRole', models.BooleanField(default=False, verbose_name='是否允许新增用户角色')),
                ('isCheckoutRole', models.BooleanField(default=False, verbose_name='是否允许切换用户角色')),
                ('userStatus', models.SmallIntegerField(choices=[(0, 'workpre'), (1, 'working'), (2, 'workout')], default=1, verbose_name='用户状态')),
                ('real_avatar', models.CharField(default='', max_length=500, verbose_name='真实头像')),
                ('jobCode', models.CharField(default='', max_length=50)),
                ('isAllowAddSchedule', models.BooleanField(default=False)),
                ('is_admin_user', models.BooleanField(default=False, verbose_name='是否是后台管理人员')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'users_userinfo',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdooDingDepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('parent_dep_id', models.CharField(max_length=200)),
                ('dept_ucode', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('disporder', models.CharField(max_length=200)),
                ('name_path', models.CharField(max_length=200)),
                ('alive_flag', models.CharField(max_length=200)),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('batch_no', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '钉钉部门表(Odoo)',
                'db_table': 'intf_uuc_department',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CircleDepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('dep_name', models.CharField(max_length=200, verbose_name='部门名称')),
                ('dep_id', models.CharField(max_length=200, verbose_name='部门唯一标识')),
                ('parent_dep_id', models.CharField(max_length=200, verbose_name='上一级部门唯一标识')),
                ('dep_only_code', models.CharField(max_length=200, verbose_name='部门 Only Code')),
                ('dep_en_name', models.CharField(max_length=200, verbose_name='部门英文名称')),
                ('display_order', models.IntegerField(verbose_name='部门在钉钉展示顺序')),
                ('name_path', models.CharField(max_length=200, verbose_name='部门唯一路径')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('batch_no', models.CharField(max_length=200, verbose_name='同步批号')),
            ],
            options={
                'verbose_name': '钉钉部门表',
                'verbose_name_plural': '钉钉部门表',
                'db_table': 'circle_ding_department',
            },
        ),
        migrations.AddField(
            model_name='circleusersmodel',
            name='circle_user_id',
            field=models.IntegerField(default=0, verbose_name='星圈用户ID'),
        ),
        migrations.AddField(
            model_name='circleusersmodel',
            name='dept_id',
            field=models.CharField(default='', max_length=200, verbose_name='部门id'),
        ),
        migrations.AddField(
            model_name='circleusersmodel',
            name='ding_id',
            field=models.CharField(default='', max_length=200, verbose_name='钉钉id'),
        ),
    ]
