# Generated by Django 3.1.2 on 2022-03-14 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220224_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooDingUser2DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.CharField(max_length=200, verbose_name='钉钉人员id')),
                ('dep_id', models.CharField(max_length=200, verbose_name='钉钉部门id')),
                ('disporder', models.CharField(max_length=20)),
                ('alive_flag', models.CharField(max_length=20)),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('batch_no', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '钉钉人员与部门表(Odoo)',
                'db_table': 'intf_uuc_user_job',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdooDingUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=200, verbose_name='钉钉userid')),
                ('state_code_1', models.CharField(max_length=20, verbose_name='区号')),
                ('mobile_1', models.CharField(max_length=20, verbose_name='手机号')),
                ('usr_id', models.CharField(max_length=200, verbose_name='钉钉人员id')),
                ('work_place', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('dept_desc', models.CharField(max_length=1000)),
                ('title_desc', models.CharField(max_length=1000)),
                ('fullname', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=500)),
                ('user_ucode', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('en_workplace', models.CharField(max_length=200)),
                ('en_title_desc', models.CharField(max_length=1000)),
                ('rec_revise_time', models.DateTimeField()),
                ('rec_create_time', models.DateTimeField()),
                ('tel', models.CharField(max_length=200)),
                ('alive_flag', models.CharField(max_length=200)),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('batch_no', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '钉钉人员表(Odoo)',
                'db_table': 'intf_uuc_user',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='circleusersmodel',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='circleusersmodel',
            name='ding_id',
        ),
        migrations.CreateModel(
            name='CircleUser2DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('usr_id', models.CharField(default='', max_length=200, verbose_name='钉钉人员id')),
                ('dep_id', models.CharField(default='', max_length=200, verbose_name='钉钉部门唯一id')),
                ('is_alive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('depart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.circledepartmentmodel', verbose_name='部门id')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='人员id')),
            ],
            options={
                'verbose_name': '钉钉人员与部门关系表',
                'verbose_name_plural': '钉钉人员与部门关系表',
                'db_table': 'circle_user_department_relation',
            },
        ),
    ]
