# Generated by Django 3.1.2 on 2022-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220314_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleusersmodel',
            name='usr_id',
            field=models.CharField(default='', max_length=200, verbose_name='钉钉人员唯一id'),
        ),
    ]
