# Generated by Django 3.1.2 on 2022-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_circleusersmodel_usr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circleuser2departmentmodel',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='circleuser2departmentmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='circleuser2departmentmodel',
            name='batch_no',
            field=models.CharField(default='', max_length=200, verbose_name='batch_no'),
        ),
        migrations.AddField(
            model_name='circleuser2departmentmodel',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='部门在钉钉展示顺序'),
        ),
        migrations.AddField(
            model_name='circleuser2departmentmodel',
            name='first_dep',
            field=models.CharField(default='', max_length=200, verbose_name='first_dep'),
        ),
    ]
