# Generated by Django 3.1.2 on 2022-03-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220314_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleusersmodel',
            name='is_vote_admin',
            field=models.BooleanField(default=False, verbose_name='是否问卷投票管理员'),
        ),
    ]
