# Generated by Django 3.1.2 on 2022-08-11 13:47

from django.db import migrations, models
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_circleusersmodel_is_vote_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpTotpUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='手机号码')),
                ('url_2fa', models.CharField(blank=True, default='', max_length=500, verbose_name='双因子二维码url')),
            ],
            options={
                'db_table': 'otp_totp_users',
            },
        ),
    ]
