# Generated by Django 3.1.14 on 2023-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_otptotpusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleusersmodel',
            name='is_required_2fa',
            field=models.BooleanField(default=True, verbose_name='是否开启二因子验证'),
        ),
    ]
