# Generated by Django 3.1.14 on 2023-07-26 14:35

from django.db import migrations, models
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGEntryDepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('dep_id', models.CharField(default='', max_length=200, unique=True, verbose_name='部门标识')),
                ('dep_name', models.CharField(default='', max_length=200, verbose_name='部门名称')),
                ('parent_dep_id', models.CharField(default='entry_root', max_length=200, verbose_name='上级部门标识')),
                ('display_order', models.IntegerField(default=1, verbose_name='展示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'db_table': 'circle_esg_entry_department',
                'ordering': ['-id'],
            },
        ),
    ]
