# Generated by Django 3.1.14 on 2023-07-27 10:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_circleusersmodel_is_required_2fa'),
        ('esg', '0002_esgentrydepartmentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EsgUserModel',
        ),
        migrations.CreateModel(
            name='EsgEntryUserModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.circleusersmodel',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='esgentrydepartmentmodel',
            name='parent_dep_name',
            field=models.CharField(default='', max_length=200, verbose_name='上级部门名称'),
        ),
    ]
