# Generated by Django 3.1.14 on 2023-07-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0003_auto_20230727_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgentrydepartmentmodel',
            name='display_order',
        ),
    ]
