# Generated by Django 3.1.14 on 2023-08-09 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esg', '0004_remove_esgentrydepartmentmodel_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('dep_name', models.CharField(blank=True, default='', max_length=200, verbose_name='所属部门')),
                ('dep_id', models.CharField(blank=True, default='', max_length=200, verbose_name='部门标识')),
                ('permission_type', models.SmallIntegerField(blank=True, choices=[(1, '超级管理员'), (2, '分站管理员')], default=None, null=True)),
                ('priority', models.IntegerField(blank=True, default=1, null=True, verbose_name='权限优先级')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_esg_admin',
                'ordering': ['-id', 'priority'],
                'unique_together': {('user', 'dep_id', 'permission_type')},
            },
        ),
    ]
