# Generated by Django 3.1.14 on 2023-08-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0005_esgadminmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esgadminmodel',
            options={'ordering': ['-id', '-priority']},
        ),
    ]
