# Generated by Django 3.1.14 on 2023-08-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0006_auto_20230809_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esgadminmodel',
            options={'ordering': ['-id', 'priority']},
        ),
    ]
