# Generated by Django 3.1.14 on 2023-08-10 10:49

from django.db import migrations, models
import fosun_circle.core.db.base


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0007_auto_20230809_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGTaskActionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default=fosun_circle.core.db.base.AutoExecutor(), max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(default='', max_length=200, null=True, verbose_name='任务名称')),
                ('uid', models.CharField(default='', max_length=200, null=True, verbose_name='任务唯一标识')),
                ('tag_id', models.IntegerField(blank=True, default=1, null=True, verbose_name='任务发帖所属标签ID')),
                ('tips', models.CharField(default='', max_length=200, null=True, verbose_name='任务发帖内容提示')),
                ('credits', models.IntegerField(blank=True, default=0, null=True, verbose_name='任务发帖对应的积分')),
                ('esg_url', models.CharField(default='', max_length=500, null=True, verbose_name='跳转到ESG URL')),
                ('circle_url', models.CharField(default='', max_length=500, null=True, verbose_name='跳转到星圈URL')),
            ],
            options={
                'db_table': 'circle_esg_task_action',
                'ordering': ['-id'],
            },
        ),
    ]
