# Generated by Django 3.1.14 on 2023-08-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0009_auto_20230810_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgtaskactionmodel',
            name='circle_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='跳转到星圈URL'),
        ),
        migrations.AlterField(
            model_name='esgtaskactionmodel',
            name='esg_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='跳转到ESG URL'),
        ),
        migrations.AlterField(
            model_name='esgtaskactionmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='esgtaskactionmodel',
            name='tips',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='任务发帖内容提示'),
        ),
        migrations.AlterField(
            model_name='esgtaskactionmodel',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='任务唯一标识'),
        ),
    ]
